[package]
name = "particle_filter_create3"
version = "0.1.0"
edition = "2024"

[dependencies]
particle_filter = {git = "https://github.com/gjf2a/particle_filter"}
bit_grid = {git = "https://github.com/gjf2a/bit_grid"}
anyhow = "1.0.101"
ryu = "1.0.23"
eframe = "0.33.3"
hash_histogram = "0.14.0"
enum-iterator = "2"
crossbeam-utils = "0.8.21"
chrono = "0.4.44"
stats-ci = "0.1.1"