[package]
name = "particle_filter_create3"
version = "0.1.0"
edition = "2024"

[dependencies]
particle_filter = {git = "https://github.com/gjf2a/particle_filter"}
arg_vals = {git = "https://github.com/gjf2a/arg_vals"}
anyhow = "1.0.101"
ryu = "1.0.23"
eframe = { version = "0.34.1", features = ["default_fonts", "glow"] }
hash_histogram = "0.14.0"
enum-iterator = "2"
crossbeam-utils = "0.8.21"
chrono = "0.4.44"
stats-ci = "0.1.1"